default:
  http_metas:
    content-type: text/html

  metas:
    title:        BnB Administrative panel
    robots:       index, follow
    description:  BnB administrative panel
    keywords:     bnb
    language:     en

  stylesheets:    [ common, backend ]

  javascripts:    [ backend ]

  has_layout:     on
  layout:         layout
