cli:
  controller:
    class: sfConsoleController
  request:
    class: sfConsoleRequest
  response:
    class: sfConsoleResponse

test:
  storage:
    class: sfSessionTestStorage
    param:
      session_path: %SF_TEST_CACHE_DIR%/sessions

dev:
  i18n:
    param:
      debug: on

all:
  i18n:
    class: sfI18N
    param:
      source:               XLIFF
      debug:                off
      untranslated_prefix:  "[T]"
      untranslated_suffix:  "[/T]"
      cache:
        class: sfFileCache
        param:
          automatic_cleaning_factor: 0
          cache_dir:                 %SF_I18N_CACHE_DIR%
          lifetime:                  86400
          prefix:                    %SF_APP_DIR%
  routing:
    class: sfPatternRouting
    param:
      load_configuration: true
      suffix:             .html
      variable_prefixes:  [':']
      segment_separators: ['/', '.']
      variable_regex:     '[\w\d_]+'
      debug:              %SF_DEBUG%
      logging:            %SF_LOGGING_ENABLED%
      cache:
        class: sfFileCache
        param:
          automatic_cleaning_factor: 0
          cache_dir:                 %SF_CONFIG_CACHE_DIR%/routing
          lifetime:                  31556926
          prefix:                    %SF_APP_DIR%